#*** Config file for the GPIOs ***
#Sample Time (s)
interval: 1

#GPIO Pin Assignments
pump: 4

#MCP3008 Channels
LTChannel: 7

#SPI Bus Details
spiBus: 0
spiDevice: 0

#PWM Limits (See Docs)
pwmMax: 100.0
pwmMin: 15.0
pwmHz: 70

#ADC calibration
adcM: 0.1389
adcC: -27.505